package com.example.company_structure.model.dto;

public class CreateEmployeeRequest {
//id is not requested as id is autogenerated by the database while creating a new employee.
    private String name;
    private double salary;
    private String level; // ENTRY, MANAGER, SENIOR
    private Long departmentId;

    // No-arg constructor
    public CreateEmployeeRequest() {}

    // All-arg constructor (optional, useful for testing)
    public CreateEmployeeRequest(String name, double salary, String level, Long departmentId) {
        this.name = name;
        this.salary = salary;
        this.level = level;
        this.departmentId = departmentId;
    }

    // Getters and Setters

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getSalary() {
        return salary;
    }

    public void setSalary(double salary) {
        this.salary = salary;
    }

    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public Long getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }
}
